### ISSUE TITLE
aeb-pro?

### ISSUE THREAD

**Issue by baradhili** [TeX-Live/tlcontrib#1]
Scratching my head on this one.. have installed TexLive from current.

Running `tlmgr update -list` tells me its happy and there is nothing to update. I've added the tlcontrib repo and looking at the repo URL  directlyI can see the list of packages.

I want to install aeb-pro

But what I am seeing is things like this

    sudo tlmgr install aeb-pro
    tlmgr: package repositories
    	main = https://mirror.math.princeton.edu/pub/CTAN/systems/texlive/tlnet (verified)
    	https://mirror.ctan.org/systems/texlive/tlcontrib/ = https://mirror.ctan.org/systems/texlive/tlcontrib/ (verified)
    tlmgr install: package aeb-pro not present in repository.
    tlmgr: action install returned an error; continuing.
    tlmgr: An error has occurred. See above messages. Exiting.

Running `sudo tlmgr list | grep aeb` I get a load of  

    tlmgr: package acmtrans not found neither locally nor remote!
    .
    .
    .
    tlmgr: package aeb-pro not found neither locally nor remote!

I'm assuming I've missed the instruction on how to load in the repo in the first place? or the ctan mirror points wrong?

**Comment by norbusan** [comment]
I guess I see your problem, thanks a lot for reporting it.
You followed the advice on https://contrib.texlive.info/ which said
```
  tlmgr repository add https://mirror.ctan.org/systems/texlive/tlcontrib
  tlmgr pinning add tlcontrib "*"
```
Which in fact is incorrect, since you didn't assign the tag `tlcontrib` to the url `https://mirror.ctan.org/systems/texlive/tlcontrib`

I have now updated the page to the correct
```
  tlmgr repository add https://mirror.ctan.org/systems/texlive/tlcontrib tlcontrib
  tlmgr pinning add tlcontrib "*"
```
(note the final `tlcontrib` at the end of the first line, which was missing before)

So how can you fix that? The best way is to do
- remove the old entry: `tlmgr repository remove https://mirror.ctan.org/systems/texlive/tlcontrib/`
- add it again with the correct tag: `tlmgr repository add https://mirror.ctan.org/systems/texlive/tlcontrib tlcontrib`

After that you should be able to run `tlmgr install aeb-pro`

Note: depending on your setup it is necessary that you prefix `tlmgr` with `sudo` so that the above commands read like `sudo tlmgr ....`

Hope that helps

**Comment by baradhili** [comment]
I knew it had to be something like that :) Thanks!

**Comment by norbusan** [comment]
So does it work now?

**Comment by baradhili** [comment]
its past 10pm here - I have to test when I get into the office tomorrow :)

**Comment by norbusan** [comment]
Oh nearly same TZ as me ... here it is past 11pm ;-)

**Comment by baradhili** [comment]
Japan?

**Comment by baradhili** [comment]
worked perfectly, thanks!
